name: test_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animate_do: ^3.3.3
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.20
  google_fonts: ^6.1.0
  google_generative_ai: ^0.2.1
  html: ^0.15.4
  http: ^1.2.0
  iconsax: ^0.0.8
  linkpeek: ^1.0.0
  lottie: ^3.1.0
  palette_generator: ^0.3.3+3
  share_it: ^0.7.0
  share_plus: ^7.2.2
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
